# Generated by Django 5.0.3 on 2024-03-20 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_uuid', models.UUIDField(default=uuid.UUID('be2d2c2a-2270-41f0-a4aa-ed87ecbfbbdc'))),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geographic_info', models.CharField(blank=True, max_length=50, null=True)),
                ('users', models.ManyToManyField(to='users.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='users.project'),
        ),
    ]
