# Generated by Django 5.0.3 on 2024-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='projects',
            field=models.ManyToManyField(related_name='projects_users', to='users.project'),
        ),
    ]
