# Generated by Django 5.0.3 on 2024-03-20 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.UUIDField(default=uuid.UUID('576454b1-cdcc-4b33-9f10-7ab7f0ae22d8')),
        ),
    ]
