# Generated by Django 5.0.3 on 2024-03-20 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_project_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.UUIDField(default=uuid.UUID('0dcf2496-f6b7-461a-a619-f0074e443735')),
        ),
    ]
